config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'welcome#index'
  devise_for :users
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/views/friends/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Email</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @friends&.each do |friend| %>
                    <tr>
                        <th><%= friend.email %></th>
                        <td><%= friend.first_name %></td>
                        <td><%= friend.last_name %></td>
                        <td>
                            <%= link_to "View Profile", user_path(friend), class: 'btn btn-sm btn-success' %>
                            <%= link_to "Stop following", friendship_path(friend), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-sm btn-warning' %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>