config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'welcome#index'
  devise_for :users
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/stock.rb
# class Stock < ApplicationRecord
#     def self.new_lookup(ticker_symbol)
#         client = IEX::Api::Client.new(
#             publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
#             secret_token: Rails.application.credentials.iex_client[:secret_api_key],
#             endpoint: "https://api.iex.cloud/v1/data/core/iex_deep/#{ticker_symbol}?token=#{Rails.application.credentials.iex_client[:sandbox_api_key]}"
#         )
#         client.price(ticker_symbol)
#     end
# end

require 'httparty'

class Stock < ApplicationRecord
    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true

    def self.company_info(ticker_symbol)
        response = HTTParty.get("https://www.alphavantage.co/query?function=OVERVIEW&symbol=#{ticker_symbol}&apikey=#{Rails.application.credentials.alphavantage[:key]}")
        response.code == 200 && response.parsed_response.is_a?(Hash) ? response.parsed_response : nil
    end

    def self.company_name(ticker_symbol)
        info = company_info(ticker_symbol)
        info ? info['Name'] : nil
    end

    def self.company_symbol(ticker_symbol)
        info = company_info(ticker_symbol)
        info ? info['Symbol'] : nil
    end

    def self.new_lookup(ticker_symbol)
        response = HTTParty.get("https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=#{ticker_symbol}&apikey=#{Rails.application.credentials.alphavantage[:key]}")
        if response.code == 200 && response.parsed_response.is_a?(Hash) && response.parsed_response['Global Quote']
            last_price = response.parsed_response['Global Quote']['05. price']
            name = company_name(ticker_symbol)
            symbol = company_symbol(ticker_symbol)
            begin
                new(ticker: symbol, name: name, last_price: last_price)
                # { symbol: ticker_symbol, name: name, last_price: last_price }.to_json
            rescue => exception
                nil
            end
        else
            nil
        end
    end

    def self.check_db(ticker_symbol)
        where(ticker: ticker_symbol).first
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    def search
        params[:stock].present? ? @stock = Stock.new_lookup(params[:stock]) : flash[:alert] = "Please enter a symbol to search."
        respond_to do |format|
            unless @stock == nil
                format.turbo_stream { render turbo_stream: turbo_stream.replace("result", partial: "users/result", locals: { stock: @stock }) }
                format.html { render 'users/my_portfolio' }
            else
                flash.now[:alert] ||= "Please enter a valid symbol to search."
                format.html { redirect_to my_portfolio_path, alert: flash.now[:alert] }
            end
        end
    end
end

app/helpers/stocks_helper.rb
module StocksHelper
  def stock_tracking_message(user, stock)
    if user.stock_already_tracked?(stock.ticker)
      "#{stock.name} is already in your portfolio."
    elsif !user.under_stock_limit?
      "You are already tracking 10 stocks."
    end
  end
end

app/views/stocks/_list.html.erb
<div class="row">
    <div class="col-9">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th scope="col">Ticker</th>
                    <th scope="col">Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @tracked_stocks&.each do |stock| %>
                    <tr>
                        <th scope="row"><%= stock.ticker %></th>
                        <td><%= stock.name %></td>
                        <td><%= stock.last_price %></td>
                        <td>
                            <% if current_user.can_track_stock?(stock.ticker) %>
                                <%= form_with url: user_stocks_path(user: current_user, ticker: stock.ticker), method: :post, local: false do %>
                                <%= submit_tag "Add to portfolio", class: "btn btn-success" %>
                                <% end %>
                            <% elsif current_user.id != @user.id %>
                                <span class="badge badge-secondary stock-message">
                                    <%= stock_tracking_message(current_user, stock) %>
                                </span>
                            <% end %>
                            <% if current_user.id == @user.id %>
                                <%= link_to "Remove", user_stock_path(stock), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'btn btn-sm btn-warning' %>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>