config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'welcome#index'
  devise_for :users
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'
  get 'my_friends', to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def under_stock_limit?
    stocks.count < 10
  end

  def stock_already_tracked?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def can_track_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_tracked?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  def self.search(param)
    param.strip!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} like ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end

  def my_friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    @search_performed = true
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends) if @friends
      unless @friends.empty?
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace("result", partial: "users/friend_result", locals: { friends: @friends }) }
          format.html { render 'users/my_friends' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "User not found."
          format.turbo_stream { render turbo_stream: turbo_stream.replace("result", partial: "users/friend_result", locals: { friends: nil }) }
          format.html { render 'users/my_friends', alert: flash.now[:alert] }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search."
        format.turbo_stream { render turbo_stream: turbo_stream.replace("result", partial: "users/friend_result", locals: { friends: nil }) }
        format.html { render 'users/my_friends', alert: flash.now[:alert] }
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_result.html.erb
<% if @search_performed && @friends && !@friends.empty? %>
  <div class="card card-header results-block">
    <table class="col-md-12">
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td><strong>Name: </strong> <%= friend.full_name %></td>
            <td><strong>Email: </strong> <%= friend.email %></td>
            <td><strong>Actions: </strong> <%= link_to "View Profile", user_path(friend), class: "btn btn-sm btn-success" %></td>
            <td>
              <% if current_user.not_friends_with?(friend.id) %>
                <%= form_with url: friendships_path(friend: friend), method: :post do %>
                  <%= submit_tag "Follow friend?", class: "btn btn-sm btn-success" %>
                <% end %>
              <% else %>
                <span class="badge badge-secondary friend-message">
                  You are friends.
                </span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% elsif alert %>
  <div class="alert alert-warning results-block">
    <%= alert %>
  </div>
<% elsif notice %>
  <div class="alert alert-success results-block">
    <%= notice %>
  </div>
<% end %>

app/views/users/_result.html.erb
<% if @stock %>
  <div class="card card-header results-block">
      <strong>Symbol: </strong> <%= @stock.ticker %>
      <strong>Name: </strong> <%= @stock.name %>
      <strong>Price: </strong> <%= @stock.last_price %>
      <% if current_user.can_track_stock?(@stock.ticker) %>
        <%= form_with url: user_stocks_path(user: current_user, ticker: @stock.ticker), method: :post, local: false do %>
          <%= submit_tag "Add to portfolio", class: "btn btn-success" %>
        <% end %>
      <% else %>
        <span class="badge badge-secondary stock-message">
          <%= stock_tracking_message(current_user, @stock) %>
        </span>
      <% end %>
  </div>
<% elsif alert %>
  <div class="alert alert-warning results-block">
    <%= alert %>
  </div>
<% elsif notice %>
  <div class="alert alert-success results-block">
    <%= notice %>
  </div>
<% end %>

app/views/users/my_friends.html.erb
<h1>Friends</h1>

<div class="search-area">
    <h3>Search Friends</h3>
    <%= form_with url: search_friend_path, method: :get, data: {turbo_frame: "result"} do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<%= turbo_frame_tag "result" do %>
    <%= render 'users/friend_result' %>
<% end %>

<div id="friends-table">
    <% unless @friends&.empty? %>
        <%= render 'friends/list' %>
    <% end %>
</div>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
    <h3>Search Stocks</h3>
    <%= form_with url: search_stock_path, method: :get, data: {turbo_frame: "result"} do %>
        <div class="form-group row">
            <div class="col-sm-9 no-right-padding">
                <%= text_field_tag :stock, nil, placeholder: "Stock ticker symbol", autofocus: true, class: "form-control form-control-lg" %>
            </div>
            <div class="col-sm-3 no-left-padding">
                <%= button_tag type: :submit, class: "btn btn-success" do %>
                    <%= fa_icon 'search 2x' %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<%= turbo_frame_tag "result" do %>
    <%= render 'users/result' %>
<% end %>

<% unless @tracked_stocks&.empty? %>
    <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header results-block">
  <table class= "col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>Email: </strong> <%= @user.email %></td>
        <td>
        <% if current_user.not_friends_with?(@user.id) %>
          <%= form_with url: friendships_path(friend: @user), method: :post do %>
            <%= submit_tag "Follow friend?", class: "btn btn-sm btn-success" %>
          <% end %><td>
        <% else %>
          <span class="badge badge-secondary friend-message">
            You are friends.
          </span>
        <% end %>
      </tr>
    </tbody>
  </table>
</div>

<% unless @tracked_stocks&.empty? %>
    <%= render 'stocks/list' %>
<% else %>
  <p class="lead">This user is not tracking any stocks.</p>
<% end %>